# Generated by Django 5.1.4 on 2025-01-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='airline_id',
            new_name='airline',
        ),
    ]
