# Generated by Django 5.1.4 on 2025-01-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_rename_airline_id_leg_airline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='id_agent',
            new_name='agent',
        ),
    ]
