# Generated by Django 5.1.4 on 2025-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0004_airline_cod_leg_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='cod',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
